sudo: false
language: node_js
node_js:
- node
script:
- npm run lint
- npm run flow
- npm run check
- npm run browsertest
- npm run coverage
dist: trusty
sudo: false
os: linux
addons:
  apt:
    packages:
      - xvfb
before_script:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
env:
  matrix:
    secure: pu+Ia+KRh9CdjXwCYNQ2/2uXoUoZ6k8uMNIgJ39+Qr5FSrhvlzuoHjNjuXrm/gRz4pO7vsXr7Fmr68X9oeMoDm8L8tb7dEIuoL7ti1dlVUt/PvdFcSadyIt/+xCpMjv6oA3rKulQfJbXQSahwciqWCt1zhXVXn6PLRFS2hdh/IeZWLjDrzLHDK0Qk/+PUfe5Wk6S9m8h5vt3RiVCCpAuJJz6UuOCfvrYegb0DhvxuIuDtKA5uC9LOkFsXYSX1RZoVStxikAZaPYrYN1R7FK8PlC/4+TiCvD4NVhcqPBL2CyLtCV6S12TMB2O26b8ROYATlSEB1O7snJf+BB3NJWrTAAqWWW6KveqZa1THJwK5gXj7pkSkBIVp6A2I0zb/vlnNiWVAleTgT8EVtTyGbtlFk8BQjIL+ou7ucTNhi2GGP7kyPxrDiLTGzQVb0wW9MaQDYtkFp1Ji2ijF6/3B09fwFG1ShBB4Tqokxr+eRB53h8UXl0pfQyIduIHNg/ucqD242uGoP8fqt+PFHTcFexLM2/6W8NS/fIqXnDkdy4WZsPHT45Dz1iPEVKQ6qJw/vmSrz1qCGqga22ShecuLhsJOYs4LrH1Hi0/2tCmZ36T2G77CviI+tKjzp307X52tEUmRbPcqGwoR58/6bM7ClQaUeE2J3Dm7DxhOr4bcT6TGgA=

before_deploy:
  - zip -q -r latest *
  - mkdir -p deploy_code_upload
  - "mv latest.zip deploy_code_upload/$TRAVIS_COMMIT.zip"

deploy:
  - provider: s3
    access_key_id: &access_key_id_staging
      secure: "0cUgenowgPhqwpSwnTbc3eITcLdKBzVKNy6RpFO23yj/V7CoJ6TbC2L1IutRwu4Pf5soQ4zOHcZ87WRA38BvUS9wjj4eUcplWgg6z9SrbomwfKKiUcXam9gQZd3Rlzi378Qi06ZkLiaHMZNeCEwGFDlZCJ5fc9ary5Pj5SokwFzt6hi7NdtEftdaLtGzN7YZhvDW5OYVXdzSkYOpSjXcU22HEU6uQ8RXocXRQSz0mxvbCGejHfTXCxfocFG2n0PHoslBdY9XLCEz4fih0RminpMLtGaNPtC4KlxiVNB3cdekT8yGFQdL4w8qy+PsUYyKZ9w6hYDyUWVe6I9MYCRS1/w7SLJ2raAEnR/i46RQ55jk8tXyj4/UqB/MysvhQ2/+EEg9eRaAFvLKOW6MtHsZGLoamHnCKqHgWz4G5xCKq4KHPubQAgAmqLPPlWHLpGpt52NOZWzhIu+X2x/Z2HFEQgEwqjdYs+Ht9ad4u9SzRQSOtHUlY30gzV41rpkSNTVKECwPnLuKIp7NZNfNqvCoAu3I3XXNpyMNM4jdm0qzdIVpJ0iBE84bo1jSOIrRoc1bP/BDApy6rWDr8kmf3RWEkKkz5dyy2dbS4t6LRvoVG7CoZ6DMR1ArMqsbAQufMuA8f7Lt1jJhS6S/XcXudb8WbkdJqz7AI+3bAuomKF4wPlk="
    secret_access_key: &secret_access_key_staging
      secure: "dh8nMWvu5r0kvy2dJQ8p2U3g8DjJwoiuvr2oxS4N2vRCId9tqLg9G0No68grakEpewhJUESuyf7ns729JZQPYQCtKoKqLEux0Ym+UujTNzcfma/YllUNMi81hMIaa8HQ0+O1j29sThlfaIaFc9zoho9D2CZw8ILDdGhJeShWgN82MyyX7t3lToNIvyIX+TN9ZrXmuWuvlFajJx5v5f1PKpclWiVqIr8prf1PRRkikNJE0fw/B5gUcVp2Fyhpr65YnZOGMsFL4pEzK5dXK0XJiBeT7gd3Tx5noEz1n1bWpuMrPhe77v4/nLCdrl+ytE8lNs7yqirgZ8lrl7LaJ/4WfakZtDFzNf9yvnkW4Gt0yom34U8VhZ0fGY1nDRrLFcYNv6h3XtacaWBg3xVsL5kz/EL/nnNYqOL+PoXH952oEMIpNRtglrggVnqcuvmuKueYUx5xmVh2BZ6LHjM7oLfYCD3P62AyxcDDT4UIL5RJRaLuahWjSiLl2fT5PLWdO3xISYo83L/k7Rp4iuHCNe/R6qmMaf5Vfc9XpCH4KEBDvzAr8KKg4VKQJ8F1hvm7Tr+AiUgIaAOj6ALo4QuXueIBK3hdSm2SyZ9NXrRhmluA7ChFdXhgPnHWOOYBFj5FzACz6kEewV1sek8I9dJoS6USaUU479RNRSwhuZR0AlAipUw="
    local_dir: deploy_code_upload
    skip_cleanup: true
    on: &deploy_on_staging
      branch: staging
    bucket: &s3_bucket_staging
      secure: "soPxr/H5fNiDNa4hppQOXdNG6qjPaw023MyQ55/jgYWhd5SoJ0D5azvF9Q5+JQMOT/dsofGQDKLtI7nEA9jBUVSyP7V+gx87ZcsoY7bDmzEaq3NY2xzRX0g30oZ7BHpgiknBL3OpqtyXgywVcpm80COb4w3f2v4kVvCm10b8cSwE1J/JLqcGSx70npTYMQE/g93exME5652vfFmDwluBc1qcoec6inceE/EbyXZpozqoiof08vJc+jLSlRIB2V2ylPJ8s9OGaYBe0YbpPsB281R2cRMwwjbxqP187z3FQIUvsVKx/K9HHeg13U+H8pGyawsUaIJTPRLKOypxcTNavopCpOSDAwR7nhnee1Xfc3t8znAtK+5THqMMjliBPTHUVenUDdGjSM8nyqaRdGD4PU4IeYXSkKyPqvh0S/5Dxi6VMkdNLlk2mVRVGGHkCbXTZjb8q2DRb+R4UPimfVaw6F0IIIXcHHp2JrbJ9tsedvubWGEH6P9wwxquw4sm3dsLIv8OrrCm9SHpaFkSUklXN62IIxGKmISe1O+DkFKFXQUs3LcIwJ02wcjjPJ9pf38KxAGpe+3yqiNGgmgN0XWKg3WwCx+fIDqTBweNplhMTMrLte+E5lz5hTbnFo9mFVUUMRRDMuH4gaCO2ZgDH4XCZYXDnju+gd/KB/SXZKIroX0="
    region: us-west-2
  - provider: codedeploy
    access_key_id: *access_key_id_staging
    secret_access_key: *secret_access_key_staging
    bucket: *s3_bucket_staging
    region: us-west-2
    key: "$TRAVIS_COMMIT.zip"
    bundle_type: zip
    application: &application_staging
      secure: "szhdBMyKVqnUl6PG3inA9APL1Fgeck8RcGYwhK1WlkmkdtMefAMpxVrC1hfJFM7uMIyZuQv58T8QDs+FtAvtBIaa7EUHgaVtjsjiRkJqZbnbRSTY2znfHjsmhXL20cMsvudLxKO1XFk798AgmQAaIQbB/NcaVWqI7M2C27p8f+JMtaKVKW0sX9i9MdaRM1UfynArcrfoVCNMGmjJb1hAy+a9QPfGcjVX26KEhEksYeiFxTvuk4LsWGs9gXxv9JTqENFkoXmCq/PVFH0x/+wY1ACNQTAm/bNzeXBqaqJEJ5NYscSrX9IogsjYrSXxe0h3d8QheYvejdnpyIWLI92sPmMAJtoTBAWI2NGymnywNYej153M5PJQkeMKbIaus+5fUKcrG7uHzSw/WDk5a6Nuo8XfsCpXxsZCZtGFmzQZUOkylvA1FK+mWp4gAoLXor2/hTx0jdJa9EQ5o2Nis4un9Rq+TCB9ymFxG/5OvHx7hoKu2sw9tLniXIMs19pyWl82+LXb4EspWV9v0ZuZHnfK+1Xmmx8QXfV0x1TN3huyQ5d0sTJw35muPNdXQFmCBBh3oEGK+0wrIjNtwP5f0Koqd/9D6DeFGltVMKOVUww4j8xukF3UNae/RpasKLXb5E1QoOldw5XiU5dSnwGIkULAk/8pG4sRabuYZCYGUOQYtGQ="
    deployment_group: *application_staging
    on: *deploy_on_staging
